// https://docusaurus.io/docs/sidebar

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// noinspection JSUnusedGlobalSymbols
export default {
  guide: [
    {
      type: 'autogenerated',
      dirName: 'guide',
    },
  ],
  support: [
    {
      type: 'autogenerated',
      dirName: 'support',
    },
  ],
} satisfies SidebarsConfig;
