import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

export default {
  guide: [
    {
      type: 'category',
      label: 'Visualization',
      link: {
        type: 'generated-index',
        description:
          'On Alljson the content can be queried with these features',
      },
      items: [
        'guide/Visualization/text-representation-of-json',
        'guide/Visualization/compare-panels-view',
        'guide/Visualization/tree-view-in-vertical-or-compact-form',
        'guide/Visualization/tree-view-in-horizontal-form',
        'guide/Visualization/arc-diagram-view',
        'guide/Visualization/table-view',
        'guide/Visualization/3d-view',
        'guide/Visualization/editor-view',
        'guide/Visualization/format-view',
      ],
    },
    {
      type: 'category',
      label: 'Query System',
      link: {
        type: 'generated-index',
        description: 'Query JSON using JSONata, XPath, XSLT, and regex.',
      },
      items: [
        'guide/query-system/jsonata-queries',
        'guide/query-system/xpath-queries',
        'guide/query-system/xslt-transformations',
        'guide/query-system/regular-expressions',
        'guide/query-system/jmespath-queries',
      ],
    },
    {
      type: 'category',
      label: 'HTTP Client and Automation',
      link: {
        type: 'generated-index',
        description:
          'Automate JSON requests and processing using HTTP clients.',
      },
      items: [
        'guide/http-client-and-automation/intro-http-client',
        'guide/http-client-and-automation/http-requests',
        'guide/http-client-and-automation/http-variables',
        'guide/http-client-and-automation/script',
      ],
    },
  ],
  support: [
    {
      type: 'autogenerated',
      dirName: 'support',
    },
  ],
} satisfies SidebarsConfig;
